// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6gaXZ5Y-gkDKohtPqEHrhQJy-LuR53WE',
    appId: '1:540012277394:web:ddafe44f4a9d3b28b7404b',
    messagingSenderId: '540012277394',
    projectId: 'amdproject-674fc',
    authDomain: 'amdproject-674fc.firebaseapp.com',
    storageBucket: 'amdproject-674fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-bSE2IsJJ5BnZB50igce37jMxvDZR8KA',
    appId: '1:540012277394:android:dcd4271d16403c4ab7404b',
    messagingSenderId: '540012277394',
    projectId: 'amdproject-674fc',
    storageBucket: 'amdproject-674fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwOipvsy1QagkLbT60mL-nNBH-YbCKv1s',
    appId: '1:540012277394:ios:25aad94202d136cbb7404b',
    messagingSenderId: '540012277394',
    projectId: 'amdproject-674fc',
    storageBucket: 'amdproject-674fc.firebasestorage.app',
    iosClientId: '540012277394-qtjlq5tf154tbguvn2av9bdcmfdjh7p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gathering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwOipvsy1QagkLbT60mL-nNBH-YbCKv1s',
    appId: '1:540012277394:ios:25aad94202d136cbb7404b',
    messagingSenderId: '540012277394',
    projectId: 'amdproject-674fc',
    storageBucket: 'amdproject-674fc.firebasestorage.app',
    iosClientId: '540012277394-qtjlq5tf154tbguvn2av9bdcmfdjh7p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gathering',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6gaXZ5Y-gkDKohtPqEHrhQJy-LuR53WE',
    appId: '1:540012277394:web:1dbbda6aeff68e5fb7404b',
    messagingSenderId: '540012277394',
    projectId: 'amdproject-674fc',
    authDomain: 'amdproject-674fc.firebaseapp.com',
    storageBucket: 'amdproject-674fc.firebasestorage.app',
  );
}
